#include "config.h"
#include "offline_pattern.h"
#include "local_display_assets.h"

#define OFFLINE_PATTERN_SEQ_TOTAL_SINGLE 0x10U

#define OFFLINE_PATTERN_ROW_MASK(maskValue) \
    (uint8_t)((maskValue) & 0xFFU), (uint8_t)(((maskValue) >> 8) & 0xFFU)

/* Store every local pattern in the same 36-byte single-layer layout used by compact playback buffers. */
static const uint8_t code g_offlinePatternDiamond[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x03C0U),
    OFFLINE_PATTERN_ROW_MASK(0x07E0U),
    OFFLINE_PATTERN_ROW_MASK(0x0FF0U),
    OFFLINE_PATTERN_ROW_MASK(0x1FF8U),
    OFFLINE_PATTERN_ROW_MASK(0x3FFCU),
    OFFLINE_PATTERN_ROW_MASK(0x7FFEU),
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    OFFLINE_PATTERN_ROW_MASK(0x7FFEU),
    OFFLINE_PATTERN_ROW_MASK(0x3FFCU),
    OFFLINE_PATTERN_ROW_MASK(0x1FF8U),
    OFFLINE_PATTERN_ROW_MASK(0x0FF0U),
    OFFLINE_PATTERN_ROW_MASK(0x07E0U),
    OFFLINE_PATTERN_ROW_MASK(0x03C0U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    0xFFU, 0x24U, 0x00U
};

static const uint8_t code g_offlinePatternCross[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    0x20U, 0xD0U, 0xFFU
};

static const uint8_t code g_offlinePatternJluEmblem[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0x7FFCU),
    OFFLINE_PATTERN_ROW_MASK(0x4104U),
    OFFLINE_PATTERN_ROW_MASK(0x4104U),
    OFFLINE_PATTERN_ROW_MASK(0x4104U),
    OFFLINE_PATTERN_ROW_MASK(0x410FU),
    OFFLINE_PATTERN_ROW_MASK(0x416CU),
    OFFLINE_PATTERN_ROW_MASK(0x80D9U),
    OFFLINE_PATTERN_ROW_MASK(0x41B2U),
    OFFLINE_PATTERN_ROW_MASK(0x337CU),
    OFFLINE_PATTERN_ROW_MASK(0x4CF0U),
    OFFLINE_PATTERN_ROW_MASK(0x4004U),
    OFFLINE_PATTERN_ROW_MASK(0x4104U),
    OFFLINE_PATTERN_ROW_MASK(0x2108U),
    OFFLINE_PATTERN_ROW_MASK(0x3018U),
    OFFLINE_PATTERN_ROW_MASK(0x0C60U),
    OFFLINE_PATTERN_ROW_MASK(0x0380U),
    0x20U, 0x60U, 0xFFU
};

static const uint8_t code g_offlinePatternChecker[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    OFFLINE_PATTERN_ROW_MASK(0xAAAAU),
    OFFLINE_PATTERN_ROW_MASK(0x5555U),
    0xFFU, 0xFFU, 0xFFU
};

static const uint8_t code g_offlinePatternBorder[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0xFFFFU),
    0xFFU, 0xFFU, 0xFFU
};

static const uint8_t code g_offlinePatternDiagonalX[OFFLINE_PATTERN_FRAME_BYTES] =
{
    OFFLINE_PATTERN_SEQ_TOTAL_SINGLE,
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    OFFLINE_PATTERN_ROW_MASK(0x4002U),
    OFFLINE_PATTERN_ROW_MASK(0x2004U),
    OFFLINE_PATTERN_ROW_MASK(0x1008U),
    OFFLINE_PATTERN_ROW_MASK(0x0810U),
    OFFLINE_PATTERN_ROW_MASK(0x0420U),
    OFFLINE_PATTERN_ROW_MASK(0x0240U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0180U),
    OFFLINE_PATTERN_ROW_MASK(0x0240U),
    OFFLINE_PATTERN_ROW_MASK(0x0420U),
    OFFLINE_PATTERN_ROW_MASK(0x0810U),
    OFFLINE_PATTERN_ROW_MASK(0x1008U),
    OFFLINE_PATTERN_ROW_MASK(0x2004U),
    OFFLINE_PATTERN_ROW_MASK(0x4002U),
    OFFLINE_PATTERN_ROW_MASK(0x8001U),
    0xFFU, 0xFFU, 0xFFU
};

static uint8_t OfflinePattern_ReadBitmapPixel(const uint8_t code *frame, uint8_t row, uint8_t col)
{
    uint8_t imageRow;
    uint16_t bitmapOffset;
    uint16_t rowBits;

    imageRow = (uint8_t)((OFFLINE_PATTERN_ROWS - 1U) - row);
    bitmapOffset = 1U + (uint16_t)imageRow * 2U;
    rowBits = (uint16_t)frame[bitmapOffset];
    rowBits |= (uint16_t)frame[bitmapOffset + 1U] << 8;
    if ((rowBits & (uint16_t)(0x8000U >> col)) != 0U)
    {
        return 0xFFU;
    }

    return OFFLINE_PATTERN_BG_RGB332;
}

uint8_t OfflinePattern_GetCount(void)
{
    return OFFLINE_PATTERN_COUNT;
}

const uint8_t code *OfflinePattern_GetFrame(uint8_t patternIndex)
{
    if (patternIndex >= OFFLINE_PATTERN_COUNT)
    {
        patternIndex = OFFLINE_PATTERN_IDX_DIAMOND;
    }

    if (patternIndex == OFFLINE_PATTERN_IDX_CROSS)
    {
        return g_offlinePatternCross;
    }

    if (patternIndex == OFFLINE_PATTERN_IDX_JLU_EMBLEM)
    {
        return g_offlinePatternJluEmblem;
    }

    if (patternIndex == OFFLINE_PATTERN_IDX_CHECKER)
    {
        return g_offlinePatternChecker;
    }

    if (patternIndex == OFFLINE_PATTERN_IDX_BORDER)
    {
        return g_offlinePatternBorder;
    }

    if (patternIndex == OFFLINE_PATTERN_IDX_DIAGONAL_X)
    {
        return g_offlinePatternDiagonalX;
    }

    return g_offlinePatternDiamond;
}

uint8_t OfflinePattern_GetPixel(uint8_t patternIndex, uint8_t row, uint8_t col)
{
    const uint8_t code *frame;

    if ((row >= OFFLINE_PATTERN_ROWS) || (col >= OFFLINE_PATTERN_COLS))
    {
        return OFFLINE_PATTERN_BG_RGB332;
    }

    frame = OfflinePattern_GetFrame(patternIndex);
    return OfflinePattern_ReadBitmapPixel(frame, row, col);
}
